accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('register/', views.registerPageView, name = 'register'),
    path('login/', views.loginPageView, name ='login'),
    path('logout/', views.logOutView, name ='logout'),
    path('customer/<str:pk>/', views.customer, name = 'customer'),
    path('products/', views.products, name = 'products'),
    path('ordercreate/<str:pk>/', views.orderCreate, name = 'ordercreate'),
    path('orderupdate/<str:pk>/', views.orderUpdate, name = 'orderupdate'),
    path('customercreate/', views.customerCreate, name = 'customercreate'),
    path('customerupdate/<str:pk>/', views.customerUpdate, name = 'customerupdate'),
    path('customerdelete/<str:pk>', views.customerDelete, name = 'customerdelete'),
    path('orderdelete/<str:pk>', views.orderDelete, name = 'orderdelete'),
    path('user/', views.userPageView, name = 'user'),
    path('accountsettings/', views.accountSettingsPage, name = 'account'),

    # django's forget password system with custom templates
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

crm/urls.py
from django.contrib import admin
from django.urls import path, include
# to display the images in the static file in the url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#Model Description : Customer model
class Customer(models.Model):
    # assigning a user to be a customer when registering 
    user = models.OneToOneField(User, null=True, on_delete = models.CASCADE)
    name = models.CharField(max_length=250, null=True)
    email = models.CharField(max_length=300, null=True)
    phone = models.CharField(max_length=20, null=True)
    profile_pic = models.ImageField(null = True)
    date_created = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return self.name

#Model Description : Tag model
class Tag(models.Model):
    name = models.CharField(max_length=250, null=True)

    def __str__(self):
        return self.name

#Model Description : Product model 
class Product(models.Model):
    #choices for category (set of tuples with keyValue)
    CATEGORY = (
        ('Sports', 'Sports'),
        ('Decor', 'Decor'),
        ('Food', 'Food')
    )
    name = models.CharField(max_length=250, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=250, null=True, choices=CATEGORY)
    details = models.TextField(blank=True)
    date_created = models.DateField(auto_now=True, null=True) 
    #Many to many relationship to allow having more than one reference
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

#Model Description : Product model 
class Order(models.Model):
    #choices for status (set of tuples with keyValue)
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered')
    )

    # link with the cus and pro models
    customer = models.ForeignKey(Customer, null=True, on_delete = models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateField(auto_now=True, null=True)
    status = models.CharField(max_length=150, null=True, choices=STATUS)

    def __str__(self):
        return self.customer.name + ' - ' + self.product.name

accounts/forms.py
from django.forms import ModelForm
from .models import Order, Customer
# getting the django builtin user form
from django.contrib.auth.forms import UserCreationForm
# getting the django builtin user model to put in the usercreationform
from django.contrib.auth.models import User

# form class for order  
class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
    # any specific form functions like filter and stuff will go here

# form class for customer  
class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        # any specific form functions like filter and stuff will go here

# form class for custom UserCreationForm
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import CreateUserForm,OrderForm, CustomerForm
# to allow multiple create fields 
from django.forms import inlineformset_factory
# allow search fields
from .filters import OrderFilter
# getting django's built in user form
from django.contrib.auth.forms import UserCreationForm
# for getting the flash messages
from django.contrib import messages
# for login autheticate and logout
from django.contrib.auth import login,authenticate,logout
# for now use this way, on big project use middleware
from django.contrib.auth.decorators import login_required
# for custom decorators 
from .decorators import authenticated_user_decorator, admin_only_decorator, restrict_role_decorator
# to access the auth group model
from django.contrib.auth.models import Group

# Create your views here.

# View for registration
@authenticated_user_decorator
def registerPageView(request):
    # usually this is done using middleware but at the moment lets do it manually

    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
        # all the user registration stuffs are done on signals now    
            # get the group to be assigned
            # group = Group.objects.get(name = 'customer')
            # user.groups.add(group) 
            # # to assign the new user as a customer
            # Customer.objects.create(
            #     user = user
            # )
            # get the username
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account created for '+ username)
            return redirect('accounts:login')

    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)

# View for login
@authenticated_user_decorator
def loginPageView(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('accounts:home')
        else:
            messages.info(request, 'Username or Password Incorrect')
    context = {}
    return render(request, 'accounts/login.html', context)

# View for logout
def logOutView(request):
    logout(request)
    return redirect('accounts:login')

# View for login
def userPageView(request):
    orders = request.user.customer.order_set.all()
    #for the stats. orders count - total, pending, delivered
    order_total_count = orders.count()
    order_pending_count = orders.filter(status='Pending').count()
    order_delivered_count = orders.filter(status='Delivered').count()
    context = {
        'orders': orders,
        'order_total_count': order_total_count,
        'order_pending_count': order_pending_count,
        'order_delivered_count': order_delivered_count,
    }
    return render(request, 'accounts/user.html', context)

# user settings page
@login_required(login_url='accounts:login')
@restrict_role_decorator(allowed_roles=['customer'])
def accountSettingsPage(request):
    customer = request.user.customer
    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
    context = {
        'form': form
    }
    return render(request, 'accounts/account_settings.html', context)

# View for home
@login_required(login_url='accounts:login')
@admin_only_decorator
@restrict_role_decorator(allowed_roles=['admin'])
def home(request):
    # getting all the model objects
    orders = Order.objects.all()
    customers = Customer.objects.all()
    products = Product.objects.all()
    customers_count = customers.count()

    #for the stats. orders count - total, pending, delivered
    order_total_count = orders.count()
    order_pending_count = orders.filter(status='Pending').count()
    order_delivered_count = orders.filter(status='Delivered').count()

    context = {
        'customers':customers,
        'products':products,
        'orders':orders,
        'order_total_count':order_total_count,
        'order_pending_count':order_pending_count,
        'order_delivered_count':order_delivered_count,
        }
    return render(request, 'accounts/dashboard.html', context)

# View for product
@login_required(login_url='accounts:login')
def products(request):
    #getting all the product objects from the DB
    products = Product.objects.all()
    return render(request, 'accounts/products.html', {'products': products})

# View for customer
@login_required(login_url='accounts:login')
def customer(request, pk):
    #getting specific customer object from the DB
    customer = Customer.objects.get(id = pk)
    # getting the child class stuff, format - var objectsRelatedToChild = parentClass.ChildClass_set.all()
    customer_all_orders = customer.order_set.all()
    order_count = customer_all_orders.count()
    # getting the filter 
    myorderFilter = OrderFilter(request.GET, queryset=customer_all_orders)
    customer_all_orders = myorderFilter.qs
    context = {
        'customer': customer,
        'customer_all_orders':customer_all_orders,
        'order_count':order_count,
        'myorderFilter': myorderFilter,
    }
    return render(request, 'accounts/customer.html', context)

# View for order create
@login_required(login_url='accounts:login')
def orderCreate(request, pk):
    OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'), extra=3)
    #get specific customer
    customer = Customer.objects.get(id = pk)
    # importing the form for order creation note: initial sets the specific variable
    #form = forms.OrderForm(initial={'customer': customer})
    # pass a set of form instead 
    formset = OrderFormSet(queryset=Order.objects.none(), instance=customer)

    if request.method == 'POST':
        #form = forms.OrderForm(request.POST)
        formset = OrderFormSet(request.POST, instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('/')

    context = {
        'formset': formset,
    }
    return render(request, 'accounts/order_form.html', context)

# View for order update
@login_required(login_url='accounts:login')
def orderUpdate(request, pk):
    # get the specific order data
    order = Order.objects.get(id = pk)
    form = forms.OrderForm(instance = order)

    if request.method == 'POST':
        form = forms.OrderForm(request.POST, instance = order)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'form': form,
    }
    return render(request, 'accounts/order_form.html', context)

# View for customer create
@login_required(login_url='accounts:login')
def customerCreate(request):
    form = forms.CustomerForm()

    if request.method == 'POST':
        form = forms.CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form': form,
    }
    return render(request, 'accounts/customer_form.html', context)

# View for customer update
@login_required(login_url='accounts:login')
def customerUpdate(request, pk):
    #get specific customer
    customer = Customer.objects.get(id = pk)
    form = forms.CustomerForm(instance = customer)

    if request.method == 'POST':
        form = forms.CustomerForm(request.POST, instance = customer)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form': form,
    }
    return render(request, 'accounts/customer_form.html', context)

# View for customer delete
def customerDelete(request, pk):
    customer = Customer.objects.get(id = pk)
    if request.method == 'POST':
        customer.delete()
        return redirect('/')
    context = {
        'item': customer,
    }
    return render(request, 'accounts/delete_page.html', context)

# View for order delete
def orderDelete(request, pk):
    order = Order.objects.get(id = pk)
    if request.method == 'POST':
        order.delete()
        return redirect('/')
    context = {
        'item': order,
    }
    return render(request, 'accounts/delete_page.html', context)

accounts/templates/accounts/account_settings.html
{%  extends 'accounts/main.html' %}
{% load static %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'accounts:home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >
		
		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">
			
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
		
			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>



{% endblock %}

accounts/templates/accounts/customer.html
{% extends 'accounts/main.html' %}

{% block content %}
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:customerupdate' customer.id %}">Update Customer</a>
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'accounts:ordercreate' customer.id %}">Create Order</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Email: {{customer.email}}</p>
			<p>Phone: {{customer.phone}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{order_count}}</h1>
		</div>
	</div>
</div>


<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">
				{{myorderFilter.form}}
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
	
</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th>Date Ordered</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
				{% for order in customer_all_orders %}
					<tr>
						<td>{{order.product.name}}</td>
						<td>{{order.product.category}}</td>
						<td>{{order.date_created}}</td>
						<td>{{order.status}}</td>
						<td><a class="btn btn-primary  btn-sm btn-info" href="">Update</a></td>
						<td><a class="btn btn-primary  btn-sm btn-danger" href="">Remove</a></td>
					</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/customer_form.html
{% extends 'accounts/main.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Send</button>
{% endblock %}    

</form>

accounts/templates/accounts/dashboard.html
{% extends 'accounts/main.html' %}

{% block content %}
<!-- stats -->
{% include 'accounts/status.html' %}

<!-- All the dashboard specific items go here -->
<br>

<div class="row">
	<div class="col-md-5">
		<h5>CUSTOMERS:</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'accounts:customercreate' %}">Create Customer</a>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Customer</th>
					<th>Phone</th>
				</tr>
				{% for i in customers %}
					<tr>
						<td><a class="btn btn-primary  btn-sm btn-secondary" href="{% url 'accounts:customer' i.id %}">View</a></td>
						<td>{{i.name}}</td>
						<td>{{i.phone}}</td>
					</tr>
				{% endfor %}

			</table>
		</div>
	</div>

	<div class="col-md-7">
		<h5>LAST 5 ORDERS</h5>
		<hr>
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
				{% for i in orders %}
					<tr>
						<td>{{i.customer.name}}</td>
						<td>{{i.date_created}}</td>
						<td>{{i.status}}</td>
						<td><a class="btn btn-primary  btn-sm btn-info" href="{% url 'accounts:orderupdate' i.id %}">Update</a></td>
						<td><a class="btn btn-primary  btn-sm btn-danger" href="{% url 'accounts:orderdelete' i.id %}">Remove</a></td>
					</tr>
				{% endfor %}
		
			</table>
		</div>
	</div>

</div>

{% endblock %}

    

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

                </div>
                
                {% for message in messages %}
                {{message}}
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>
                    <div class="d-flex justify-content-center links">
						Forgot password? <a href="{% url 'accounts:reset_password' %}" class="ml-2">Reset password</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

accounts/templates/accounts/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <title>TLH CRM</title>
</head>
<body>
    {% include 'accounts/navbar.html' %} <!--you can include other html files as well(anywhere) -->

    {% block content %}
    <div class="container-fluid"></div>
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

accounts/templates/accounts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">CRM</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if request.user.is_staff %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:home' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:products' %}">Products</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:account' %}">Settings</a>
        </li>
        {% endif %}
      </ul>
    </div>
    <span class="hello-msg">Hello, {{request.user}}</span>
    <span ><a  class="hello-msg" href="{% url 'accounts:logout' %}">Logout</a></span>
  </nav>

accounts/templates/accounts/order_form.html
{% extends 'accounts/main.html' %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{formset.management_form }}
                {% for form in formset %}
                    <hr>
                    {{form}}
                {% endfor %}
                <button type="submit">Send</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}    


accounts/templates/accounts/password_reset.html
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>

accounts/templates/accounts/password_reset_done.html
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="/">Log in</a>

accounts/templates/accounts/password_reset_sent.html
<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}

{% block content %}
<br>

		<div class="row">
			<div class="col-md">
				<div class="card card-body">
					<h5>Products</h5>
				</div>
				<div class="card card-body">
					<table class="table">
						<tr>
							<th>Product</th>
							<th>Category</th>
							<th>Price</th>
						</tr>
						{% for i in products %}
							<tr>
							<td>{{i.name}}</td>
							<td>{{i.category}}</td>
							<td>{{i.price}}</td>
						</tr>
						{% endfor %}
						
					</table>
				</div>
			</div>
			
		</div>
{% endblock %}

accounts/templates/accounts/status.html
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h4 class="card-title">{{order_total_count}}</h4>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h4 class="card-title">{{order_delivered_count}}</h4>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h4 class="card-title">{{order_pending_count}}</h4>
			  	</div>
			</div>
		</div>
	</div>
</div>

accounts/templates/accounts/user.html
{% extends 'accounts/main.html' %}

{% block content %}
{% include 'accounts/status.html' %}
<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th>Date Ordered</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
				{% for order in orders %}
					<tr>
						<td>{{order.product.name}}</td>
						<td>{{order.product.category}}</td>
						<td>{{order.date_created}}</td>
						<td>{{order.status}}</td>
						<td><a class="btn btn-primary  btn-sm btn-info" href="">Update</a></td>
						<td><a class="btn btn-primary  btn-sm btn-danger" href="">Remove</a></td>
					</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>
{% endblock %}